[control_plane]
cp1 ansible_host=node1.pve.homelab.nicologiuliani.site
cp2 ansible_host=node2.pve.homelab.nicologiuliani.site
cp3 ansible_host=node3.pve.homelab.nicologiuliani.site

[workers]
w1 ansible_host=node4.pve.homelab.nicologiuliani.site
w2 ansible_host=node5.pve.homelab.nicologiuliani.site

[k8s:children]
control_plane
workers

[k8s:vars]
ansible_user=debian
ansible_ssh_private_key_file=ssh_key/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new' #non chiedere conferma per l'aggiunta della chiave host al known_hosts
