vip: "<VIP>"
vip_port: 8443
vrrp_pass: "CHANGE_ME"

pod_cidr: "10.244.0.0/16"
calico_version: "v3.30.3"

longhorn_version: "v1.12.1"
longhorn_replicas: 2

metallb_version: "v0.16.1"
metallb_pool: "<METALLB_POOL_START>-<METALLB_POOL_END>"
web_ip: "<WEB_IP>"
